# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-08 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.IntegerField()),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=70)),
                ('Edad', models.IntegerField()),
                ('Telefono', models.CharField(max_length=12)),
                ('Correo', models.EmailField(max_length=254)),
                ('Domicilio', models.TextField()),
            ],
        ),
    ]
