# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-08 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20180407_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='Vacuna',
            field=models.ManyToManyField(blank=True, to='mascota.Vacuna'),
        ),
    ]
